### ISSUE TITLE
Has anyone tested this on DCC++EX?

### ISSUE THREAD

**Issue by FrightRisk** [newHeiko/wiFred#16]
Any WiThrottle device should work, but since we don't broadcast our info to WiThrottle and expect WiThrottle to ask and get back our ID string, some throttles may need to account for that. Creating a DCC++EX Command Station from an Uno or Mega is easier than building a throttle, so I was hoping someone already tested or could make a CS with an Arduino and Motor Shield they may have already. It can be tested with just an Arduino, a WiFi shield or ESP-01S and a computer connected as a serial monitor since we can turn on wifi and Withrottle diagnostics and watch if commands are being sent back and forth. That way you don't have to have a motor shield and actually use it as a CS connected to a track.

**Comment by newHeiko** [comment]
I haven't - but if you send me a DCC++EX sketch for a NodeMCU (with ESP12F) or an ESP32-S2-DevKit https://www.olimex.com/Products/IoT/ESP32-S2/ESP32-S2-DevKit-Lipo/open-source-hardware I'm happy to try it. I don't have any motor shield or anything, so please give detailed info how to test...

I did test it with an LNWI, which also does not broadcast its information and also expects wiThrottle to ask, and I made it work.

Heiko

**Comment by newHeiko** [comment]
@FrightRisk A colleague of mine tested this with DCC++Ex and got it to work after a little shuffling around the initialization. So it should work since  #62290d501ff1ae78cc65b820608219e5dc9286e6

Feel free to re-open if it doesn't,
Heiko
